/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hrkj_nativetest_HelloNative */

#ifndef _Included_hrkj_nativetest_HelloNative
#define _Included_hrkj_nativetest_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hrkj_nativetest_HelloNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hrkj_nativetest_HelloNative_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
